// <auto-generated />
namespace MoviesWebAPIApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _checked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_checked));
        
        string IMigrationMetadata.Id
        {
            get { return "201509150024249_checked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
